# Generated by Django 5.0 on 2024-11-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course_details",
            fields=[
                ("roll_no", models.IntegerField(primary_key=True, serialize=False)),
                ("course", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("roll_no", models.IntegerField(primary_key=True, serialize=False)),
                ("hobbys", models.CharField(max_length=100)),
            ],
        ),
    ]
