# Generated by Django 5.0 on 2024-11-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("application_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Applied", "Applied"),
                            ("Interviewing", "Interviewing"),
                            ("Offered", "Offered"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Applied",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("job_description", models.TextField(blank=True)),
                ("resume_text", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
            ],
        ),
    ]
